"""initial

Revision ID: c6c4b787c863
Revises:
Create Date: 2026-05-03 14:36:20.990325

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6c4b787c863"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_accounts",
        sa.Column("id", sa.Integer(), nullable=False, comment="主键ID"),
        sa.Column(
            "name", sa.String(length=100), nullable=False, comment="用户昵称/姓名"
        ),
        sa.Column("email", sa.String(length=100), nullable=False, comment="登录邮箱"),
        sa.Column(
            "password", sa.String(length=255), nullable=False, comment="加密密码"
        ),
        sa.Column("status", sa.Boolean(), nullable=False, comment="账号是否启用"),
        sa.PrimaryKeyConstraint("id"),
        comment="账号表",
    )
    op.create_index(
        op.f("ix_sys_accounts_email"), "sys_accounts", ["email"], unique=True
    )
    op.create_index(op.f("ix_sys_accounts_id"), "sys_accounts", ["id"], unique=False)
    op.create_table(
        "sys_menus",
        sa.Column("id", sa.Integer(), nullable=False, comment="菜单ID"),
        sa.Column("pid", sa.Integer(), nullable=False, comment="父菜单ID"),
        sa.Column(
            "menu_type",
            sa.Integer(),
            nullable=False,
            comment="菜单类型：1-目录 2-菜单 3-按钮",
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="菜单名称"),
        sa.Column(
            "path", sa.String(length=255), nullable=False, comment="前端路由地址"
        ),
        sa.Column(
            "component", sa.String(length=255), nullable=False, comment="前端组件路径"
        ),
        sa.Column("icon", sa.String(length=100), nullable=False, comment="菜单图标"),
        sa.Column("sort", sa.Integer(), nullable=False, comment="显示顺序"),
        sa.Column("api_url", sa.String(length=255), nullable=False, comment="接口地址"),
        sa.Column(
            "api_method",
            sa.String(length=10),
            nullable=False,
            comment="请求方式：GET/POST/PUT/DELETE/*",
        ),
        sa.Column("visible", sa.Boolean(), nullable=False, comment="是否显示"),
        sa.Column(
            "status", sa.Boolean(), nullable=False, comment="状态：true-正常 false-禁用"
        ),
        sa.Column("remark", sa.String(length=500), nullable=False, comment="备注"),
        sa.PrimaryKeyConstraint("id"),
        comment="菜单表",
    )
    op.create_index(op.f("ix_sys_menus_id"), "sys_menus", ["id"], unique=False)
    op.create_table(
        "sys_roles",
        sa.Column("id", sa.Integer(), nullable=False, comment="主键ID"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="角色名称"),
        sa.Column("sort", sa.Integer(), nullable=False, comment="显示顺序"),
        sa.Column(
            "status", sa.Boolean(), nullable=False, comment="状态：true-正常 false-禁用"
        ),
        sa.Column("remark", sa.String(length=500), nullable=False, comment="备注"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="角色表",
    )
    op.create_index(op.f("ix_sys_roles_id"), "sys_roles", ["id"], unique=False)
    op.create_table(
        "sys_account_roles",
        sa.Column("account_id", sa.Integer(), nullable=False, comment="用户ID"),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色ID"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["sys_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["sys_roles.id"],
        ),
        sa.PrimaryKeyConstraint("account_id", "role_id"),
        comment="用户-角色关联表",
    )
    op.create_table(
        "sys_role_menus",
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色ID"),
        sa.Column("menu_id", sa.Integer(), nullable=False, comment="菜单ID"),
        sa.ForeignKeyConstraint(
            ["menu_id"],
            ["sys_menus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["sys_roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "menu_id"),
        comment="角色-菜单关联表",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sys_role_menus")
    op.drop_table("sys_account_roles")
    op.drop_index(op.f("ix_sys_roles_id"), table_name="sys_roles")
    op.drop_table("sys_roles")
    op.drop_index(op.f("ix_sys_menus_id"), table_name="sys_menus")
    op.drop_table("sys_menus")
    op.drop_index(op.f("ix_sys_accounts_id"), table_name="sys_accounts")
    op.drop_index(op.f("ix_sys_accounts_email"), table_name="sys_accounts")
    op.drop_table("sys_accounts")
    # ### end Alembic commands ###
